/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  
  mySidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    //   type: 'category',
    //   label: 'Account',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'Account/create-an-account',
    //     },
    //     {
    //       type: 'doc',
    //       id: 'Account/manage-personal-data',
    //     },
    //     {
    //       type: 'doc',
    //       id: 'Account/change-password',
    //     },
    //     {
    //       type: 'doc',
    //       id: 'Account/sign-off',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Security',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'Security/privacy-policy',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Tips',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'Tips/how-to-start',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Company profile',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'Company profile/create-company-profile',
    //     },
    //     {
    //       type: 'doc',
    //       id: 'Company profile/create-vacancy',
    //     },
    //     {
    //       type: 'doc',
    //       id: 'Company profile/manage-companies',
    //     },
    //     {
    //       type: 'doc',
    //       id: 'Company profile/see-company-applications',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Vacancy application',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'Vacancy application/see-likes',
    //     },
    //     {
    //       type: 'doc',
    //       id: 'Vacancy application/vacancy-application',
    //     },
        
    //   ],
    },
  ],
   
};

module.exports = sidebars;
