/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  
  mySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
    // {
    //   type: 'category',
    //   label: 'Account',
    //   items: [
    //     {
    //       type:'doc',
    //       id:'how-create-account'
    //     },
    //     {
    //       type:'doc',
    //       id:'how-edit-account',
          
    //     },

    //   ],
    // },
  ],
   
};

module.exports = sidebars;
